services:
  traefik:
    image: traefik:3.4.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - TZ=Europe/Paris
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_EMAIL=${MY_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/rules.toml:/etc/traefik/rules.toml:ro
      - ./traefik/acme.json:/etc/traefik/acme.json:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.feignman.online`)
      - traefik.http.routers.traefik.tls.certresolver=dns-cloudflare
      - traefik.http.routers.traefik.middlewares=authelia@docker

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./authelia/config:/config
      - ./authelia/logs:/var/log/authelia
      - ./authelia/secrets:/secrets:ro
    expose:
      - 9091
    environment:
      TZ: Europe/Paris
      X_AUTHELIA_CONFIG_FILTERS: 'template'
      LLDAP_AUTHELIA_PASSWORD: ${AUTHELIA_LLDAP_PASSWORD}
      SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      SMTP_EMAIL: ${MY_EMAIL}
      SMTP_PASSWORD: ${AUTHELIA_SMTP_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.feignman.online`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=dns-cloudflare"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.feignman.online"
      - "traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    restart: unless-stopped
    environment:
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=dc=feignman,dc=online
      - LLDAP_LDAP_USER_DN=admin
      - LLDAP_LDAP_USER_EMAIL=${MY_EMAIL}
      - LLDAP_LDAP_USER_PASS=${LLDAP_USER_PASSWORD}
      # - LLDAP_SMTP_OPTIONS__PASSWORD=${LLDAP_SMTP_PASSWORD}
    ports:
      - "17170:17170"
      - "3890:3890"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.rule=Host(`ldap.feignman.online`)"
      - "traefik.http.routers.lldap.entrypoints=websecure"
      - "traefik.http.routers.lldap.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"

  vaultwarden:
    image: vaultwarden/server:1.34.1-alpine
    container_name: vaultwarden
    volumes:
      - ./volumes/vaultwarden:/data/
    ports:
      - 8090:80
    environment:
      - ADMIN_TOKEN=${VAULT_ADMIN_TOKEN}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.feignman.online`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=dns-cloudflare"

  nzbget:
    image: ghcr.io/linuxserver/nzbget:version-v25.2
    container_name: nzbget
    environment:
      - PUID=3002
      - PGID=3002
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/nzbget/config:/config
      - /truenas/downloads:/downloads
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.feignman.online`)"
      - "traefik.http.routers.nzbget.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=dns-cloudflare"
      # - "traefik.http.routers.nzbget.middlewares=auth@file"
    ports:
      - 6789:6789
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:2.1.1
    container_name: deluge
    network_mode: host
    environment:
      - PUID=3002
      - PGID=3002
      - TZ=Europe/Paris
      #- UMASK_SET=022 #optional
      #- DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./volumes/deluge/config:/config
      - /truenas/downloads:/downloads
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.nzbget.rule=Host(`deluge.feignman.online`)"
      - "traefik.http.routers.nzbget.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=dns-cloudflare"
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=3002
      - PGID=993  # needs to be set to the GID of 'render' to allow GPU access
      - VERSION=docker
      - SYSCALL_MAX_ENABLED=1
      - TZ=Europe/Paris
      # - UMASK_SET=022 #optional
    volumes:
      - ./volumes/plex/config:/config
      - ./volumes/plex/transcode:/transcode
      - /truenas/Movies:/data/Movies
      - /truenas/Series:/data/Series
      - /truenas/downloads/downloaded/extra:/data/Extras
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3002
      - PGID=3002
      - TZ=Europe/Paris
      # - UMASK_SET=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - /truenas/Movies:/movies
      - /truenas/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.feignman.online`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3002
      - PGID=3002
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/config:/config
      - /truenas/Series:/series
      - /truenas/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.feignman.online`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
    ports:
      - 8989:8989
    restart: unless-stopped

  telegraf:
     container_name: telegraf
     image: telegraf:1.35
     restart: unless-stopped
     # Added for latest telegraf: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
     user: telegraf:995
     privileged: true
     environment:
       HOST_MOUNT_PREFIX: /rootfs
       HOST_RUN: /rootfs/run
       HOST_VAR: /rootfs/var
       HOST_PROC: /rootfs/proc
       HOST_SYS: /rootfs/sys
       HOST_ETC: /rootfs/etc
     volumes:
       - ./telegraf/docker-lxc-host.conf:/etc/telegraf/telegraf.conf:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /:/rootfs:ro
