server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info
  file_path: '/var/log/authelia/authelia.log'
  keep_stdout: true

identity_validation:
  elevated_session:
    require_second_factor: true
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_secret: {{ mustEnv "JWT_SECRET" | msquote }}

totp:
  disable: true
  issuer: 'feignman.online'
  period: 30
  skew: 1

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

authentication_backend:
  ldap:
    implementation: 'lldap'
    address: 'ldap://lldap:3890'
    base_dn: 'DC=feignman,DC=online'
    user: 'UID=authelia,OU=people,DC=feignman,DC=online'
    password: {{ mustEnv "LLDAP_AUTHELIA_PASSWORD" | msquote }}

access_control:
  default_policy: 'one_factor'
  rules:
    - domain: 'traefik.feignman.online'
      policy: 'one_factor'

session:
  name: 'feignman.online'
  secret: {{ mustEnv "SESSION_SECRET" | msquote }}
  same_site: 'lax'
  inactivity: '15m'
  expiration: '3h'
  remember_me: '7d'
  cookies:
    - domain: 'feignman.online'
      authelia_url: 'https://auth.feignman.online'

regulation:
  max_retries: 4
  find_time: 120
  ban_time: 300

storage:
  encryption_key: {{ mustEnv "STORAGE_ENCRYPTION_KEY" | msquote }}
  local:
    path: '/config/db.sqlite3'

# notifier:
#   disable_startup_check: false
#   filesystem:
#     filename: '/config/notification.txt'
notifier:
  smtp:
    address: 'submission://smtp.gmail.com:587'
    username: {{ mustEnv "SMTP_EMAIL" | msquote }}
    # Password can also be set using a secret: https://www.authelia.com/configuration/methods/secrets/
    password: {{ mustEnv "SMTP_PASSWORD" | msquote }}
    sender: 'Authelia <admin@feignman.online>'
    subject: "[Authelia] {title}"
